# Generated by Django 4.1.5 on 2023-09-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_unit_price_product_unit_buying_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
